########################################
#                                      #
#                WEBSERVER             #
#                                      #
########################################
Webserver:
    IP: 127.0.0.1
    Port: 8080

########################################
#                                      #
#            COMMIT FORWARDING         #
#                                      #
########################################
CommitForwarding:
    # The name of the GitHub Repository
    "ThisLightMan/GitHub-Discord-Webhooks":
        # Ensure that the secret is unique and keep it private
        Secret: "test1234"
        # The webhook URL from Discord
        Webhook: "DISCORD-WEBHOOK-URL"
        
        # The message that will get sent to Discord
        Message:
            Commits: "[``{commit-short-id}``]({commit-url}) **{commit-message}**"
            Embed:
                Color: "#157ae6"
                Title: "[{repository-name}:{branch-name}] {commit-count} new {commit-plural}"
                URL: "{compare-url}"
                Author:
                    Name: "{author-name}"
                    URL: "{author-profile}"
                    Icon: "{author-avatar}"
                Description: "{commits}"
                # What each commit in {commits} will look like
            OverflowEmbeds:
                Color: "#157ae6"
                Description: "{commits}"